### ISSUE TITLE
Redis server required?

### ISSUE THREAD

**Issue by tomlowshang** [buxx/OpenCombat#1]
Run.py tries to connect to a Redis server.

```
Traceback (most recent call last):
  File "/home/tlow/src/OpenCombat/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/home/tlow/src/OpenCombat/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/connection.py", line 541, in _connect
    raise err
  File "/home/tlow/src/OpenCombat/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tlow/src/OpenCombat/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/client.py", line 667, in execute_command
    connection.send_command(*args)
  File "/home/tlow/src/OpenCombat/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/tlow/src/OpenCombat/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/home/tlow/src/OpenCombat/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tlow/src/OpenCombat/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/home/tlow/src/OpenCombat/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/connection.py", line 541, in _connect
    raise err
  File "/home/tlow/src/OpenCombat/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 10, in <module>
    from synergine2.core import Core
  File "/home/tlow/src/OpenCombat/synergine2/synergine2/core.py", line 6, in <module>
    from synergine2.cycle import CycleManager
  File "/home/tlow/src/OpenCombat/synergine2/synergine2/cycle.py", line 11, in <module>
    from synergine2.processing import ProcessManager
  File "/home/tlow/src/OpenCombat/synergine2/synergine2/processing.py", line 10, in <module>
    from synergine2.share import SharedDataManager
  File "/home/tlow/src/OpenCombat/synergine2/synergine2/share.py", line 252, in <module>
    shared = SharedDataManager()
  File "/home/tlow/src/OpenCombat/synergine2/synergine2/share.py", line 128, in __init__
    self.clear()
  File "/home/tlow/src/OpenCombat/synergine2/synergine2/share.py", line 131, in clear
    self._r.flushdb()
  File "/home/tlow/src/OpenCombat/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/client.py", line 747, in flushdb
    return self.execute_command('FLUSHDB')
  File "/home/tlow/src/OpenCombat/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/home/tlow/src/OpenCombat/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/tlow/src/OpenCombat/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/home/tlow/src/OpenCombat/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
```

**Comment by buxx** [comment]
Hello,

You're right OpenCombat use Synergine2 who require a running redis server. I update the README right now.

Thank's for report !

**Comment by buxx** [comment]
@tomlowshang Do you try OpenCombat under linux or Windows ? I have not checked under windows yet.

**Comment by buxx** [comment]
I hope to remove this dependencies yes. Actually i use it in synergine2 to share data between processes (like map matrix). If i found a way to do the things in performing way it can be removed.

**Comment by buxx** [comment]
@tomlowshang I maybe have a solution to replace redis here: https://docs.python.org/3.8/library/multiprocessing.shared_memory.html :)
