### ISSUE TITLE
Crash when cache directory does not exist

### ISSUE THREAD

**Issue by tomlowshang** [buxx/OpenCombat#41]
Works if I create the directory. The crash hangs the program which requires a Ctrl-C to cleanup. Close window is ignored.
```
2018-01-29 15:15:30,620|synergine-Core|19097|ERROR: Fatal error during simulation
Traceback (most recent call last):
  File "/home/tlow/toms/venv/opencombat/lib/python3.6/site-packages/synergine2/core.py", line 55, in run
    self.main_process_terminal.execute_as_main_process(self)
  File "/home/tlow/toms/venv/opencombat/lib/python3.6/site-packages/synergine2/terminals.py", line 119, in execute_as_main_process
    self.start(input_queue=input_queue, output_queue=output_queue)
  File "/home/tlow/toms/venv/opencombat/lib/python3.6/site-packages/synergine2/terminals.py", line 99, in start
    self.run()
  File "/home/tlow/src/OpenCombat/opencombat/terminal/base.py", line 58, in run
    self.gui.run()
  File "/home/tlow/toms/venv/opencombat/lib/python3.6/site-packages/synergine2_cocos2d/gui.py", line 777, in run
    cocos.director.director.run(self.get_main_scene())
  File "/home/tlow/toms/venv/opencombat/lib/python3.6/site-packages/cocos/director.py", line 406, in run
    event_loop.run()
  File "/home/tlow/toms/venv/opencombat/lib/python3.6/site-packages/pyglet/app/base.py", line 142, in run
    self._run()
  File "/home/tlow/toms/venv/opencombat/lib/python3.6/site-packages/pyglet/app/base.py", line 154, in _run
    timeout = self.idle()
  File "/home/tlow/toms/venv/opencombat/lib/python3.6/site-packages/pyglet/app/base.py", line 275, in idle
    redraw_all = self.clock.call_scheduled_functions(dt)
  File "/home/tlow/toms/venv/opencombat/lib/python3.6/site-packages/pyglet/clock.py", line 346, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "/home/tlow/toms/venv/opencombat/lib/python3.6/site-packages/synergine2_cocos2d/gui.py", line 774, in <lambda>
    lambda *_, **__: self.terminal.read(),
  File "/home/tlow/toms/venv/opencombat/lib/python3.6/site-packages/synergine2/terminals.py", line 142, in read
    self.receive(package)
  File "/home/tlow/toms/venv/opencombat/lib/python3.6/site-packages/synergine2_cocos2d/terminal.py", line 12, in receive
    self.gui.before_received(package)
  File "/home/tlow/toms/venv/opencombat/lib/python3.6/site-packages/synergine2_cocos2d/gui.py", line 824, in before_received
    self.append_subject(subject)
  File "/home/tlow/toms/venv/opencombat/lib/python3.6/site-packages/synergine2_cocos2d/gui.py", line 828, in append_subject
    subject_mapper.append(subject, self.layer_manager)
  File "/home/tlow/toms/venv/opencombat/lib/python3.6/site-packages/synergine2_cocos2d/gui.py", line 691, in append
    actor = self.actor_class(self.config, subject)
  File "/home/tlow/src/OpenCombat/opencombat/gui/actor.py", line 105, in __init__
    super().__init__('actors/man.png', subject=subject, config=config)
  File "/home/tlow/src/OpenCombat/opencombat/gui/actor.py", line 36, in __init__
    super().__init__(image_path, subject=subject, config=config)
  File "/home/tlow/toms/venv/opencombat/lib/python3.6/site-packages/synergine2_cocos2d/actor.py", line 42, in __init__
    self.path_manager.path(image_path),
  File "/home/tlow/toms/venv/opencombat/lib/python3.6/site-packages/synergine2_cocos2d/actor.py", line 83, in build_default_image
    base_image.save(final_path)
  File "/home/tlow/toms/venv/opencombat/lib/python3.6/site-packages/PIL/Image.py", line 1925, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'cache/140298218124568_man.png'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 35, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
```

**Comment by buxx** [comment]
I forgot to manage this case :p. I will do it now (i will add the cache clearing, actually it will grow without limit, it's a per-instance cache).

About "Close window is ignored": I open a new issue for it: #42

**Comment by buxx** [comment]
Solved with https://github.com/buxx/synergine2/commit/da3b9611a414acbe6f06e92fac40ddae8f2197a5 .
Note: You need to update `synergine2` code. (i use this cache folder to generate soldier image with their weapon image: i am making a system where weapon image is a separated image to be able to change soldier gui during battle :) you can test it now if no bug. Today and this week i'm working on "fire" animation )
