### ISSUE TITLE
Resource not found when tileset relative to tmx map file

### ISSUE THREAD

**Issue by buxx** [buxx/OpenCombat#45]
When tileset path is relative to tmx map file, pyglet don't found the file:

```
Traceback (most recent call last):
  File "/home/bux/Projets/synergine2/synergine2/core.py", line 55, in run
    self.main_process_terminal.execute_as_main_process(self)
  File "/home/bux/Projets/synergine2/synergine2/terminals.py", line 119, in execute_as_main_process
    self.start(input_queue=input_queue, output_queue=output_queue)
  File "/home/bux/Projets/synergine2/synergine2/terminals.py", line 99, in start
    self.run()
  File "/home/bux/Projets/OpenCombat/opencombat/terminal/base.py", line 48, in run
    map_dir_path=self.map_dir_path,
  File "/home/bux/Projets/OpenCombat/opencombat/gui/base.py", line 197, in __init__
    map_dir_path=map_dir_path,
  File "/home/bux/Projets/synergine2/synergine2_cocos2d/gui.py", line 841, in __init__
    read_queue_interval=read_queue_interval,
  File "/home/bux/Projets/synergine2/synergine2_cocos2d/gui.py", line 788, in __init__
    self.layer_manager.init()
  File "/home/bux/Projets/OpenCombat/opencombat/gui/base.py", line 145, in init
    super().init()
  File "/home/bux/Projets/synergine2/synergine2_cocos2d/layer.py", line 97, in init
    self.middleware.init()
  File "/home/bux/Projets/synergine2/synergine2_cocos2d/middleware.py", line 33, in init
    self.tmx = cocos.tiles.load(map_file_path)
  File "/home/bux/Projets/OpenCombat/venv3.5/lib/python3.5/site-packages/cocos/tiles.py", line 218, in load
    obj = load_tmx(filename)
  File "/home/bux/Projets/OpenCombat/venv3.5/lib/python3.5/site-packages/cocos/tiles.py", line 312, in load_tmx
    path = resource.find_file(tag.attrib['source'])
  File "/home/bux/Projets/OpenCombat/venv3.5/lib/python3.5/site-packages/cocos/tiles.py", line 101, in find_file
    path = pyglet.resource.location(filename).path
  File "/home/bux/Projets/OpenCombat/venv3.5/lib/python3.5/site-packages/pyglet/resource.py", line 458, in location
    raise ResourceNotFoundException(name)
pyglet.resource.ResourceNotFoundException: Resource "../shared/tilesets/trees.tsx" was not found on the path.  Ensure that the filename has the correct captialisation.
```

Override concerned methods or update on the fly the paths.

**Comment by buxx** [comment]
Fixed here: https://github.com/buxx/synergine2/commit/ae50954d348540194f9eb4bc3182c8ef1b99754a
